/**
 * A hundred arguments, written rather than found.
 *
 * Discovery mints topics from what the web is arguing about this week, which is
 * the right long-run source and a poor cold start: a cabinet with eleven rounds
 * is empty after five minutes of play. These are the evergreen ones — the
 * arguments that were already running before the internet and will outlast it.
 *
 * Every line obeys the same rules the model is held to: a specific subject,
 * answerable with LOVE or HATE and nothing else, no hint of the expected
 * answer, and never a question of fact.
 */

export type Seed = { q: string; c: string };

export const SEED_TOPICS: readonly Seed[] = [
  { q: "Pineapple on pizza?", c: "food" },
  { q: "Well-done steak?", c: "food" },
  { q: "Coriander?", c: "food" },
  { q: "Ketchup on eggs?", c: "food" },
  { q: "Truffle oil on everything?", c: "food" },
  { q: "Instant coffee?", c: "food" },
  { q: "Marmite?", c: "food" },
  { q: "Durian?", c: "food" },
  { q: "Pumpkin spice season?", c: "food" },
  { q: "Olives?", c: "food" },
  { q: "Blue cheese?", c: "food" },
  { q: "Liquorice?", c: "food" },
  { q: "Raisins in cookies?", c: "food" },
  { q: "Ice in red wine?", c: "food" },
  { q: "Milk poured before the cereal?", c: "food" },

  { q: "Dark mode everywhere?", c: "tech" },
  { q: "Tabs over spaces?", c: "tech" },
  { q: "Vim?", c: "tech" },
  { q: "Letting AI write your code?", c: "tech" },
  { q: "Crypto?", c: "tech" },
  { q: "Smart fridges?", c: "tech" },
  { q: "Phones without a headphone jack?", c: "tech" },
  { q: "Foldable phones?", c: "tech" },
  { q: "Notifications on by default?", c: "tech" },
  { q: "Open-plan offices?", c: "tech" },
  { q: "Cameras on in every meeting?", c: "tech" },
  { q: "Self-driving cars?", c: "tech" },
  { q: "Algorithmic feeds?", c: "tech" },
  { q: "Passwords instead of passkeys?", c: "tech" },
  { q: "Electric cars?", c: "tech" },

  { q: "Reality TV?", c: "culture" },
  { q: "Rebooting old films?", c: "culture" },
  { q: "Audiobooks counting as reading?", c: "culture" },
  { q: "Musicals?", c: "culture" },
  { q: "Modern art?", c: "culture" },
  { q: "Spoilers?", c: "culture" },
  { q: "Subtitles always on?", c: "culture" },
  { q: "Jazz?", c: "culture" },
  { q: "Christmas music in November?", c: "culture" },
  { q: "Poetry?", c: "culture" },
  { q: "Opera?", c: "culture" },
  { q: "Standing ovations for everything?", c: "culture" },
  { q: "Tattoos?", c: "culture" },
  { q: "Beards?", c: "culture" },
  { q: "Cargo shorts?", c: "culture" },
  { q: "Crocs?", c: "culture" },
  { q: "Socks with sandals?", c: "culture" },
  { q: "Emoji in work chat?", c: "culture" },
  { q: "Voice notes?", c: "culture" },
  { q: "Small talk?", c: "culture" },

  { q: "VAR in football?", c: "sport" },
  { q: "Golf as a sport?", c: "sport" },
  { q: "Esports as a sport?", c: "sport" },
  { q: "Five-day cricket?", c: "sport" },
  { q: "Boxing?", c: "sport" },
  { q: "Formula One?", c: "sport" },
  { q: "Penalty shootouts?", c: "sport" },
  { q: "Fantasy leagues?", c: "sport" },
  { q: "Trash talk?", c: "sport" },
  { q: "Load management?", c: "sport" },
  { q: "Instant replay?", c: "sport" },
  { q: "Anthems before games?", c: "sport" },

  { q: "Tipping culture?", c: "money" },
  { q: "Cashless shops?", c: "money" },
  { q: "Subscriptions for everything?", c: "money" },
  { q: "Buy now, pay later?", c: "money" },
  { q: "Inheritance?", c: "money" },
  { q: "Raising the minimum wage?", c: "money" },
  { q: "Billionaires?", c: "money" },
  { q: "Forgiving student debt?", c: "money" },
  { q: "The four-day week?", c: "money" },
  { q: "Return-to-office mandates?", c: "money" },
  { q: "Unpaid internships?", c: "money" },
  { q: "Haggling?", c: "money" },

  { q: "Early mornings?", c: "life" },
  { q: "Naps?", c: "life" },
  { q: "Camping?", c: "life" },
  { q: "Cats?", c: "life" },
  { q: "Dogs in restaurants?", c: "life" },
  { q: "Gym selfies?", c: "life" },
  { q: "New Year's resolutions?", c: "life" },
  { q: "Long-distance relationships?", c: "life" },
  { q: "Splitting the bill evenly?", c: "life" },
  { q: "Group holidays?", c: "life" },
  { q: "Big weddings?", c: "life" },
  { q: "Birthdays celebrated at work?", c: "life" },
  { q: "Astrology?", c: "life" },
  { q: "Alarm snooze buttons?", c: "life" },
  { q: "Sleeping with the window open?", c: "life" },

  { q: "Compulsory voting?", c: "politics" },
  { q: "Term limits?", c: "politics" },
  { q: "Monarchy?", c: "politics" },
  { q: "Nuclear power?", c: "politics" },
  { q: "Congestion charges?", c: "politics" },
  { q: "Open borders?", c: "politics" },
  { q: "Lobbying?", c: "politics" },
  { q: "Two-party systems?", c: "politics" },
  { q: "Referendums?", c: "politics" },
  { q: "Political dynasties?", c: "politics" },
  { q: "Voting at sixteen?", c: "politics" },
] as const;
